services:
    jv.arcade_bestratedgamesforumindex.listener:
        class: jv\arcade_bestratedgamesforumindex\event\listener
        arguments:
            - '@template'
            - '@jv.arcade_bestratedgamesforumindex.ext'
            - '@?jv.arcade.arcade'
            - '@?jv.arcade.config'
        tags:
            - { name: event.listener }

    jv.arcade_bestratedgamesforumindex.ext:
        class: jv\arcade_bestratedgamesforumindex\inc\acp_settings
        tags:
            - { name: jv.arcade.ext }