services:
    jv.arcade_latesthighscores.listener:
        class: jv\arcade_latesthighscores\event\listener
        arguments:
            - '@jv.arcade_latesthighscores.ext'
            - '@?jv.arcade.arcade'
            - '@?jv.arcade.config'
        tags:
            - { name: event.listener }

    jv.arcade_latesthighscores.ext:
        class: jv\arcade_latesthighscores\inc\acp_settings
        tags:
            - { name: jv.arcade.ext }