services:
    jv.arcade_whoisplayingforumindex.listener:
        class: jv\arcade_whoisplayingforumindex\event\listener
        arguments:
            - '@jv.arcade_whoisplayingforumindex.ext'
            - '@?jv.arcade.arcade'
            - '@?jv.arcade.config'
            - '@auth'
        tags:
            - { name: event.listener }

    jv.arcade_whoisplayingforumindex.ext:
        class: jv\arcade_whoisplayingforumindex\inc\acp_settings
        tags:
            - { name: jv.arcade.ext }
